import{a as w,S as v,i as a}from"./assets/vendor-hdXJlIEV.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const R="51904877-a497cebd24b125b23f704ea34",q="https://pixabay.com/api/";async function f(t,s=1,n=15){const o={key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:n};return(await w.get(q,{params:o})).data}const d=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");let E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(t,s=!1){const n=t.map(({webformatURL:o,largeImageURL:e,tags:r,likes:i,views:L,comments:b,downloads:S})=>`
    <a href="${e}" class="gallery-item">
      <div class="photo-card">
        <img src="${o}" alt="${r}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${i}</p>
          <p><b>Views:</b> ${L}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </div>
    </a>`).join("");s?d.insertAdjacentHTML("beforeend",n):d.innerHTML=n,E.refresh()}function M(){d.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function u(){document.querySelector(".loader").classList.add("hidden")}function g(){document.querySelector(".load-more").classList.remove("hidden")}function y(){document.querySelector(".load-more").classList.add("hidden")}let h="",c=1;const l=15,P=document.querySelector("#search-form"),O=document.querySelector(".load-more");P.addEventListener("submit",$);O.addEventListener("click",B);async function $(t){t.preventDefault();const s=t.currentTarget.elements.searchQuery;if(!s)return;const n=s.value.trim();if(!n){a.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}h=n,c=1,M(),y(),m();try{const o=await f(h,c,l);if(!o||!o.hits||o.hits.length===0){a.warning({title:"No results",message:"Sorry, no images found. Try another search!",position:"topRight"});return}p(o.hits,{append:!1}),Math.ceil(o.totalHits/l)>1?g():a.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"})}catch(o){console.error("❌ ERROR in onSearch:",o),a.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}finally{u()}}async function B(){c+=1,y(),m();try{const t=await f(h,c,l);p(t.hits,{append:!0});const s=Math.ceil(t.totalHits/l);c<s?g():a.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"}),u(),H()}catch(t){console.error("❌ ERROR in onLoadMore:",t),a.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),u()}}function H(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
