import{a as w,S as v,i as a}from"./assets/vendor-hdXJlIEV.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(e){if(e.ep)return;e.ep=!0;const n=s(e);fetch(e.href,n)}})();const q="51904877-a497cebd24b125b23f704ea34",B="https://pixabay.com/api/";async function h(o,r=1,s=15){const t={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s};return(await w.get(B,{params:t})).data}const d=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function f(o,r=!1){const s=o.map(({webformatURL:t,largeImageURL:e,tags:n,likes:i,views:E,comments:S,downloads:R})=>`
    <a href="${e}" class="gallery-item">
      <div class="photo-card">
        <img src="${t}" alt="${n}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${i}</p>
          <p><b>Views:</b> ${E}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${R}</p>
        </div>
      </div>
    </a>`).join("");r?d.insertAdjacentHTML("beforeend",s):d.innerHTML=s,M.refresh()}function D(){d.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function p(){document.querySelector(".loader").classList.add("hidden")}function g(){document.querySelector(".load-more").classList.remove("hidden")}function y(){document.querySelector(".load-more").classList.add("hidden")}let u="",c=1;const l=15,L=document.querySelector("#search-form"),b=document.querySelector(".load-more");console.log("DEBUG: searchForm =",L);console.log("DEBUG: loadMoreBtn =",b);L.addEventListener("submit",P);b.addEventListener("click",O);async function P(o){o.preventDefault(),console.log("DEBUG: onSearch triggered ✅");const r=o.currentTarget.elements.searchQuery;if(!r){console.error("❌ ERROR: searchQuery input not found");return}const s=r.value.trim();if(!s){a.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}u=s,c=1,D(),y(),m();try{const t=await h(u,c,l);if(console.log("DEBUG: fetchImages response =",t),!t||!t.hits||t.hits.length===0){a.warning({title:"No results",message:"Sorry, no images found. Try another search!",position:"topRight"});return}f(t.hits,{append:!1}),Math.ceil(t.totalHits/l)>1?g():a.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"})}catch(t){console.error("❌ ERROR in onSearch:",t),a.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}finally{p()}}async function O(){console.log("DEBUG: onLoadMore triggered ✅"),c+=1,y(),m();try{const o=await h(u,c,l);console.log("DEBUG: fetchImages response (load more) =",o),f(o.hits,{append:!0});const r=Math.ceil(o.totalHits/l);c<r?g():a.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"}),G()}catch(o){console.error("❌ ERROR in onLoadMore:",o),a.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{p()}}function G(){const o=document.querySelector(".gallery").firstElementChild;if(!o)return;const{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
